# Разогрев

## Задание 1

Иногда, когда нужно создавать много однотипных лямбда функций, еще удобнее будет создать функцию, которая будет их генерировать.

Реализуйте функцию ``mod_checker(x, mod=0)``, которая будет **возвращать лямбда функцию** от одного аргумента ``y``, которая будет возвращать ``True``, если остаток от деления ``y`` на ``x`` равен ``mod``, и ``False`` иначе.

Если в ``return`` вашей функции написано выражение, отличное от лямбда функции - задание считается проваленным

**Sample:**

```python
mod_3 = mod_checker(3)

print(mod_3(3)) # True
print(mod_3(4)) # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4)) # True
```

In [1]:
def mod_checker(x, mod=0):
    return lambda y: y % x == mod

mod_3 = mod_checker(3)

print(mod_3(3))
print(mod_3(4))

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4))

True
False
True


# Numpy

In [2]:
import numpy as np

## Задание 2
Напишите функцию, которая принимает один аргумент - ``n``. Функция должна создать нампаевскую матрицу размером ``(n, n)`` и залить ее шахматным узором. Порядок узора не имеет значения, важен общий паттерн.

**Sample:**
```python
chess_maze(8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [3]:
def chess_maze(n):
    res = np.zeros((n, n), int)
    flag = True
    for row, el in enumerate(res):
        for element, position in enumerate(el):
            res[row][element] = np.invert(flag)
            flag = not flag
        flag = not flag

    return res

print(chess_maze(4))

print()

print(chess_maze(8))

print()

print(chess_maze(16))

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


## Задание 3
Напишите функцию, которая принимает 2 аргумента ``arr`` и ``exclude_values``. ``arr`` - это одномерный нампаевский массив, в котором необходимо поменять знак всем числам (инвертировать), которые есть в массиве ``exclude_values``. Действия необходимо делать прямо в исходном массиве, не создавая копий.

**Sample:**
```python
#Исходный вектор 
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
 
my_func(arr, exclude_values)
array([ 0  1  2  3 -4 -5 -6 -7  8  9 10])
```

In [4]:
def exclude_values(arr, exclude_values):
    for i, val in enumerate(arr):
        if val in exclude_values:
            arr[i] *= -1
    return arr

In [5]:
## Задание 3
arr = np.arange(10+1)
values = np.arange(4, 8)

print(exclude_values(arr, values))
print()

arr = np.arange(100+1)
values = np.arange(4, 80)

print(exclude_values(arr, values))
print()

arr = np.arange(25+1)
values = np.arange(20, 40)

print(exclude_values(arr, values))

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]

[  0   1   2   3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 -30 -31 -32 -33 -34 -35
 -36 -37 -38 -39 -40 -41 -42 -43 -44 -45 -46 -47 -48 -49 -50 -51 -52 -53
 -54 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64 -65 -66 -67 -68 -69 -70 -71
 -72 -73 -74 -75 -76 -77 -78 -79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 -20 -21 -22 -23 -24 -25]


## Задание 4
Напишите функцию, которая принимает одномерный положительный нампаевский массив и минимум 4 раза выводит на экран (функция ``print``) этот же массив, в котором у элементов оставлена только целая часть. Все >= 4 раза функция должна использовать разные методы для извлечения целой части.

**Sample:**
```python
#Исходный вектор 
arr = np.random.uniform(low=10, high=100,size=20)
#Исходный вектор arr:
arr
[99.54707368 49.26237526 80.50565073 10.10998238 16.39378916 60.64633657
 25.49637622 31.06574268 94.48636127 73.41204506 75.70638137 70.43830146
 72.28607422 40.59319738 57.85802554 35.39428061 55.25707514 48.00020145
 38.39449991 26.19085017]
 
my_func(arr)

[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99 49 80 10 16 60 25 31 94 73 75 70 72 40 57 35 55 48 38 26]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
```

В примере 5 выводов print из функции, просто чтобы были :)

In [6]:
import math

In [7]:
def print_integer_fraction(arr):
    # using int
    for val in arr:
        print(int(val), end=" ")
    print()

    # using math.floor
    for val in arr:
        print(math.floor(val), end=" ")
    print()

    # using math.trunc
    for val in arr:
        print(math.trunc(val), end=" ")
    print()

    # using // 1
    for val in arr:
        print(f"{(val // 1):.0f}", end=" ")
    print()

In [8]:
arr = np.random.uniform(low=10, high=100,size=20)
# Исходный вектор arr:
print(arr)

print_integer_fraction(arr)

[38.79119074 35.74655693 13.69184343 78.80233602 37.90542229 78.29692215
 56.67721802 94.06742002 44.44303021 49.88379828 66.92829642 26.54019187
 51.70168591 24.12286251 19.0741647  97.79164052 89.29532705 54.11741042
 72.93998733 77.93392634]
38 35 13 78 37 78 56 94 44 49 66 26 51 24 19 97 89 54 72 77 
38 35 13 78 37 78 56 94 44 49 66 26 51 24 19 97 89 54 72 77 
38 35 13 78 37 78 56 94 44 49 66 26 51 24 19 97 89 54 72 77 
38 35 13 78 37 78 56 94 44 49 66 26 51 24 19 97 89 54 72 77 


## Задание 5
Напишите функцию, которая принимает два числа - ``N`` и ``p``. ``N`` - это размер стороны квадратной матрицы np.zeros, ``p`` - это количество индексов в матрице (p не превышает N*N), которые нужно заменить на случайные числа. Индексы и числа нужно выбирать случайно. Функция должна возвращать квадратную матрицу со стороной ``N``, в которой ровно ``p`` чисел заменены на случайные.

```python
my_func(N=6, p=4)

[[56.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [99.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   0.]]
```

In [9]:
import random

In [10]:
def change_p_indices(N, p):
    if p > N**2:
        return None

    square_matrix = np.zeros((N, N))
    indices = random.sample(range(N**2), p)
    rand_values = [random.random() for _ in range(p)]

    for i, value in zip(indices, rand_values):
        square_matrix[i // N][i % N] = value

    return square_matrix

In [11]:
print(change_p_indices(N=6, p=4))

[[0.94045534 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.35622964 0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.54682323 0.        ]
 [0.         0.         0.91826791 0.         0.         0.        ]]


In [12]:
print(change_p_indices(N=6, p=34))

[[0.34897119 0.87598227 0.32291176 0.32399836 0.35666514 0.37573448]
 [0.01842534 0.07408288 0.77914124 0.86646283 0.58633599 0.94912247]
 [0.91611621 0.50350442 0.6254464  0.56254127 0.04632178 0.34309758]
 [0.28595596 0.88184817 0.         0.98303672 0.31946552 0.90304761]
 [0.3523481  0.05368646 0.         0.65423574 0.18932564 0.63136944]
 [0.378082   0.46191728 0.95349967 0.27416665 0.93993814 0.68443267]]


In [13]:
print(change_p_indices(N=6, p=37))

None


# Pandas

In [14]:
import pandas as pd

# Задание 6

Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и четыре наблюдения в каждой колонке:

```
type value
B    18.

B    20.

C    10.

C    -10.
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [15]:
my_data = pd.DataFrame({'type': ['B', 'B', 'C', 'C'], 'value': [18, 20, 10, -10]})
my_data['type'] = my_data['type'].astype(str)
my_data['value'] = my_data['value'].astype(float)
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    4 non-null      object 
 1   value   4 non-null      float64
dtypes: float64(1), object(1)
memory usage: 192.0+ bytes


In [16]:
my_data['type'] = my_data['type'].astype('category')
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      float64 
dtypes: category(1), float64(1)
memory usage: 288.0 bytes


In [17]:
my_data['value'] = my_data['value'].astype('float16')
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      float16 
dtypes: category(1), float16(1)
memory usage: 264.0 bytes


In [18]:
my_data

type  value
0    B   18.0
1    B   20.0
2    C   10.0
3    C  -10.0

# Задание 7
Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и десять тысяч (10 000) наблюдений в каждой колонке. В колонке ``type`` должно быть 10 уникальных значений.

```python
my_data.shape
____________
(10000, 2)
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

Во сколько раз уменьшился размер исходного датафрейма после выполнения этих двух операций?

In [19]:
types = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
my_data = pd.DataFrame(columns={'type', 'value'})

# picking a rand type out of 10 letters
type_data = [random.choice(types) for i in range(10000)]
value_data = np.random.rand(10000)

my_data = my_data.assign(type=type_data, value=value_data)

# changing types
my_data['type'] = my_data['type'].astype(str)
my_data['value'] = my_data['value'].astype(float)

In [20]:
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    10000 non-null  object 
 1   value   10000 non-null  float64
dtypes: float64(1), object(1)
memory usage: 156.4+ KB


In [21]:
my_data['type'] = my_data['type'].astype('category')
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    10000 non-null  category
 1   value   10000 non-null  float64 
dtypes: category(1), float64(1)
memory usage: 88.4 KB


# the size of dataframe after switching to type column to category type decreased almost 2 times

In [22]:
my_data['value'] = my_data['value'].astype('float16')
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    10000 non-null  category
 1   value   10000 non-null  float16 
dtypes: category(1), float16(1)
memory usage: 29.8 KB


# after changing two columns by their representative more lightweight datatypes original size decreased by (156/29.8) ~= 5.23 times

#### Для решения дальнейших задач мы будем использовать следующий датасет, загрузите его с помощью команды:

In [23]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

In [24]:
df

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
4     0  10.0  B -1.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[500 rows x 4 columns]

Примечание: все операции с исходным датафреймом должны быть ``inplace``. То есть исходный датафрейм в переменной ``df`` **должен** измениться

# Задание 8

В переменную с именем subset_1 сохраните только первые 19 строк и только 1 и 3 колонку.

В переменную с именем subset_2 сохраните все строки кроме 2, 3 и 18 и только 2 и 4 колонку.

In [25]:
subset_1 = df.iloc[:19, [0, 2]]
subset_1

V1 V3
0    2  B
1   -1  B
2    0  A
3    2  A
4    0  B
5    2  A
6    0  A
7    1  A
8    0  B
9   -1  A
10   1  A
11  -2  A
12   0  B
13   1  A
14  -1  A
15   2  B
16   0  B
17   0  A
18   0  A

In [26]:
subset_2 = df.drop([1, 2, 17]).iloc[:, [1, 3]]
subset_2

V2   V4
0    13.0  1.0
3    11.0  2.0
4    10.0 -1.0
5    11.0  0.0
6     9.0  2.0
..    ...  ...
495   8.0 -1.0
496   8.0  1.0
497  11.0  2.0
498  11.0  2.0
499   8.0  1.0

[497 rows x 2 columns]

# Задание 9

В переменную subset_3 сохраните только те наблюдения, у которых значения переменной V1 строго больше 0, и значение переменной V3  равняется 'A'.

В переменную  subset_4  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.

In [27]:
subset_3 = df[df['V1'] > 0]
subset_3

V1    V2 V3   V4
0     2  13.0  B  1.0
3     2  11.0  A  2.0
5     2  11.0  A  0.0
7     1   9.0  A  1.0
10    1  10.0  A  1.0
..   ..   ... ..  ...
491   4   7.0  A  2.0
494   1  11.0  A  1.0
495   1   8.0  A -1.0
496   3   8.0  A  1.0
498   1  11.0  A  2.0

[161 rows x 4 columns]

In [28]:
subset_4 = df[(df['V2'] != 10) | (df['V4'] >= 1)]
subset_4

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
5     2  11.0  A  0.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[447 rows x 4 columns]

# Задание 10
Добавьте следующие колонки в df:

1) V5 = V1 + V4
2) V6 = **натуральный** логарифм переменной V2

In [29]:
df['V5'] = df['V1'] + df['V4']
df.head()

V1    V2 V3   V4   V5
0   2  13.0  B  1.0  3.0
1  -1   7.0  B  1.0  0.0
2   0  11.0  A  0.0  0.0
3   2  11.0  A  2.0  4.0
4   0  10.0  B -1.0 -1.0

In [30]:
df['V6'] = np.log(df['V2'])
df.head()

V1    V2 V3   V4   V5        V6
0   2  13.0  B  1.0  3.0  2.564949
1  -1   7.0  B  1.0  0.0  1.945910
2   0  11.0  A  0.0  0.0  2.397895
3   2  11.0  A  2.0  4.0  2.397895
4   0  10.0  B -1.0 -1.0  2.302585

# Задание 11

Переименуйте колонки в df.

1) V1 -> session_value

2) V2 -> group

3) V3 -> time

4) V4 -> n_users

In [31]:
df

V1    V2 V3   V4   V5        V6
0     2  13.0  B  1.0  3.0  2.564949
1    -1   7.0  B  1.0  0.0  1.945910
2     0  11.0  A  0.0  0.0  2.397895
3     2  11.0  A  2.0  4.0  2.397895
4     0  10.0  B -1.0 -1.0  2.302585
..   ..   ... ..  ...  ...       ...
495   1   8.0  A -1.0  0.0  2.079442
496   3   8.0  A  1.0  4.0  2.079442
497  -1  11.0  B  2.0  1.0  2.397895
498   1  11.0  A  2.0  3.0  2.397895
499   0   8.0  B  1.0  1.0  2.079442

[500 rows x 6 columns]

In [32]:
df = df.rename(columns={'V1': 'session_value', 'V2': 'group', 'V3': 'time', 'V4': 'n_users'})
df

session_value  group time  n_users   V5        V6
0                2   13.0    B      1.0  3.0  2.564949
1               -1    7.0    B      1.0  0.0  1.945910
2                0   11.0    A      0.0  0.0  2.397895
3                2   11.0    A      2.0  4.0  2.397895
4                0   10.0    B     -1.0 -1.0  2.302585
..             ...    ...  ...      ...  ...       ...
495              1    8.0    A     -1.0  0.0  2.079442
496              3    8.0    A      1.0  4.0  2.079442
497             -1   11.0    B      2.0  1.0  2.397895
498              1   11.0    A      2.0  3.0  2.397895
499              0    8.0    B      1.0  1.0  2.079442

[500 rows x 6 columns]

# Задание 12
В датафрейме ``my_stat`` в колонке ``session_value`` замените все пропущенные значения на нули.

В колонке ``n_users`` замените все отрицательные значения на медианное значение переменной ``n_users`` (без учета отрицательных значений, разумеется).

In [33]:
my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')

In [34]:
my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            NaN    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            NaN    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

In [35]:
my_stat['session_value'] = my_stat['session_value'].fillna(0)
my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            0.0    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            0.0    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

In [36]:
mean_val = my_stat['n_users'].mean()
my_stat['n_users'] = my_stat['n_users'].apply(lambda x: mean_val if x < 0 else x)
my_stat

session_value  time group  n_users
0            0.0    12     B      9.0
1            0.0    11     A      0.7
2            1.0     8     A      1.0
3            2.0     9     B      3.0
4            2.0    10     B      9.0
5            3.0     8     A      8.0
6            0.0    11     B      5.0
7            0.0     9     A      4.0
8            0.0     8     B      0.7
9            0.0     9     A      0.7