#Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [104]:
def reverse_number(a):
    return int((str(abs(a))[::-1]))

print(reverse_number(123))
print(reverse_number(120))
print(reverse_number(-123))
print(reverse_number(-12123413))
print(reverse_number(12123413))

321
21
321
31432121
31432121


#Выколотый квадрат


Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [105]:
def make_square(n):
    for i in range(n):
        for j in range(n):
            if j < 1 or i < 1 or j == n - 1 or i == n - 1:
                print('*', end=' ')
            else:
                print(' ', end=' ')
        print()


make_square(5)
make_square(10)
make_square(15)

* * * * * 
*       * 
*       * 
*       * 
* * * * * 
* * * * * * * * * * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
*                 * 
* * * * * * * * * * 
* * * * * * * * * * * * * * * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
*                           * 
* * * * * * * * * * * * * * * 


#Пермутации

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

In [106]:
import itertools

def permutations(a):
    return [list(i) for i in itertools.permutations(a)]


print(permutations([1, 2, 3]))
print(permutations([0, 1]))
print(permutations([1]))
print(permutations([23, 123, 1241, 2314, 231]))

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]
[[0, 1], [1, 0]]
[[1]]
[[23, 123, 1241, 2314, 231], [23, 123, 1241, 231, 2314], [23, 123, 2314, 1241, 231], [23, 123, 2314, 231, 1241], [23, 123, 231, 1241, 2314], [23, 123, 231, 2314, 1241], [23, 1241, 123, 2314, 231], [23, 1241, 123, 231, 2314], [23, 1241, 2314, 123, 231], [23, 1241, 2314, 231, 123], [23, 1241, 231, 123, 2314], [23, 1241, 231, 2314, 123], [23, 2314, 123, 1241, 231], [23, 2314, 123, 231, 1241], [23, 2314, 1241, 123, 231], [23, 2314, 1241, 231, 123], [23, 2314, 231, 123, 1241], [23, 2314, 231, 1241, 123], [23, 231, 123, 1241, 2314], [23, 231, 123, 2314, 1241], [23, 231, 1241, 123, 2314], [23, 231, 1241, 2314, 123], [23, 231, 2314, 123, 1241], [23, 231, 2314, 1241, 123], [123, 23, 1241, 2314, 231], [123, 23, 1241, 231, 2314], [123, 23, 2314, 1241, 231], [123, 23, 2314, 231, 1241], [123, 23, 231, 1241, 2314], [123, 23, 231, 2314, 1241], [123, 1241, 23, 2314, 231], [123, 1241, 23, 231, 2314], [123, 1241, 2

### Почти двойной факториал
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [107]:
def almost_double_factorial(n):
    if n <= 1:
        return 1
    if n % 2 == 1:
        n -= 1
    return n * almost_double_factorial(n - 1)

print(almost_double_factorial(5))
print(almost_double_factorial(6))
print(almost_double_factorial(7))
print(almost_double_factorial(8))
print(almost_double_factorial(25))

8
48
48
384
1961990553600


In [108]:
N = 25
#YOUR CODE
N_double_fact = almost_double_factorial(N)

assert N_double_fact == 1961990553600, "Something is wrong! Please try again"

N = 100
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 34243224702511976248246432895208185975118675053719198827915654463488000000000000, "Something is wrong! Please try again"

### Хитрая сортировка

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [109]:
from operator import itemgetter

items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key=lambda x: x[1][-1])
                      
assert sorted_items == [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')], \
"Something is wrong! Please try again"

### Еще строки

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [110]:
def my_func(s, a, b):
    op_counter = 0

    while a in s:
        s = s.replace(a, b)
        op_counter += 1

        if op_counter > 1000:
            print("Impossible")
            return
    
    print(op_counter)

my_func("abab", "ab", "ba")
my_func("ababa", "a", "b")
my_func("ababa", "b", "a")
my_func("ababa", "c", "c")
my_func("ababac", "c", "c")

my_func("hehexd", "he", "xd")

2
1
1
0
Impossible
1


### Создание массивов
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

In [130]:
def cumsum_and_erase(A, erase=1):
    res = []
    total = 0
    for x in A:
        total += x
        res.append(total)
    try:
        res.remove(erase)
    except:
        pass
    return res

A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

### Обработка текста
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [131]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

def process(sentences):
    return [' '.join(filter(str.isalpha, i.split())) for i in sentences]

assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

#Расстояние Хэмминга

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [132]:
def hamming(str1, str2):
    counter = 0
    for i in range(len(str1)):
        if str1[i] != str2[i]:
            counter += 1
    return counter

assert hamming("AGCT", "ACGT") == 2

assert hamming("helloworld", "hellokorld") == 1
assert hamming("car", "bar") == 1
assert hamming("stringone", "stringtwo") == 3

### Numpy

In [79]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [100]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.16868191 0.76106977 0.08748527 ... 0.06618747 0.028263   0.0891617 ]
 [0.05586767 0.03813743 0.94934044 ... 0.68063418 0.66802635 0.9656591 ]
 [0.1564734  0.98613924 0.78215259 ... 0.72725043 0.2865257  0.61239767]
 ...
 [0.52116545 0.02971302 0.42107635 ... 0.72631792 0.0587588  0.28761932]
 [0.826561   0.06257901 0.01767973 ... 0.10882765 0.14484958 0.20751117]
 [0.87891928 0.52565703 0.14896578 ... 0.620398   0.00216294 0.82548111]]
[[0.77113682 0.27767638 0.46542177 ... 0.83195308 0.1644715  0.84340222]
 [0.09946578 0.612293   0.4286985  ... 0.2072525  0.43884616 0.52158764]
 [0.73878541 0.96156295 0.25358061 ... 0.18767392 0.45575509 0.86766502]
 ...
 [0.8460427  0.80163684 0.34661803 ... 0.1503431  0.79352811 0.11789621]
 [0.74309492 0.34452781 0.99167262 ... 0.12818333 0.2515782  0.85458147]
 [0.07985495 0.75327788 0.46669547 ... 0.54817435 0.33115174 0.37575925]]


In [92]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy (может помочь функция zip)
    """
    res_matrix = [[0]*len(a[0])]*len(b[0])
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                res_matrix[i][j] += a[i][k] * b[k][j]

    return res_matrix

c = [[1132, 17, 33],
    [9, 4, 8],
    [100, 3, 1]]
d = [[1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]

print(mult(c, d))

[[1132, 17, 33], [9, 4, 8], [100, 3, 1]]


In [93]:
def np_mult(a, b):
    """  
    a: np.array[size, size] --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size] --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return np.matmul(a, b)

In [101]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 712 ms, sys: 0 ns, total: 712 ms
Wall time: 714 ms


In [102]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 6.29 ms, sys: 0 ns, total: 6.29 ms
Wall time: 10.1 ms


In [103]:
# проверим корректность
assert np.allclose(np.array(M1), M2)